# Generated by Django 5.2.5 on 2025-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPatient',
            fields=[
                ('PATIENTNUMBER', models.TextField(primary_key=True, serialize=False)),
                ('BDAY', models.TextField()),
                ('CONTRACT', models.TextField()),
                ('PHONE', models.TextField()),
                ('MIDDLENAME', models.TextField()),
                ('ADDRESSTYPE', models.TextField()),
                ('JURISTICPERSON', models.TextField()),
                ('LASTNAME', models.TextField()),
                ('ADDRESSTOWN', models.TextField()),
                ('WORK', models.TextField()),
                ('DOCUMENTNUMBER', models.TextField()),
                ('FIRSTNAME', models.TextField()),
                ('FORMAOPLATA', models.TextField()),
                ('ADDRESSST', models.TextField()),
                ('SC_K', models.TextField()),
                ('ADDRESSRAION', models.TextField()),
                ('ADDRESSSTR', models.TextField()),
                ('SC_SP', models.TextField()),
                ('PARTNERKEYLPU', models.TextField()),
                ('ISFIZICPERSON', models.TextField()),
                ('DOCUMENTSERIA', models.TextField()),
                ('STREET', models.TextField()),
                ('ACCOUNT', models.TextField()),
                ('TBK', models.TextField()),
                ('ADDRESSFULL', models.TextField()),
                ('RAION_GORODA', models.TextField()),
                ('SC_SP_KEY', models.TextField()),
                ('SEX', models.TextField()),
                ('YEARSOLD', models.TextField()),
                ('ADDRESSKEY', models.TextField()),
                ('KEY_ADDRESS_RAJON', models.TextField()),
                ('ADDRESSCLSKEY', models.TextField()),
                ('DATE_LPU', models.TextField()),
                ('SNILSNUMBER', models.TextField()),
                ('AUTHOR', models.TextField()),
                ('MODIFIER', models.TextField()),
                ('MODIFIED', models.TextField()),
                ('LASTAPPEAL', models.TextField()),
                ('RESIDENTID', models.TextField()),
                ('RESIDENTDATE', models.TextField()),
                ('RESIDENT', models.TextField()),
                ('KEY_LPU', models.TextField()),
                ('KEY_LPUATTACH', models.TextField()),
                ('EMAIL', models.TextField()),
                ('STARTNOEMAILDATE', models.TextField()),
                ('NOEMAIL', models.TextField()),
                ('DOCTYPE', models.TextField()),
                ('DOCSERIA', models.TextField()),
                ('DOCNUMBER', models.TextField()),
                ('ADDRESSFULLR', models.TextField()),
                ('R1ID', models.TextField()),
                ('DOG_D', models.TextField()),
                ('DISC_CARD', models.TextField()),
                ('DISCOUNTDATE', models.TextField()),
                ('TOFIO', models.TextField()),
                ('TOPHONE', models.TextField()),
                ('TOKIND', models.TextField()),
                ('WORK_POSITION', models.TextField()),
                ('CONSENTMAILING', models.TextField()),
                ('DOCNAME', models.TextField()),
            ],
            options={
                'db_table': 'PATIENTS',
                'managed': False,
            },
        ),
    ]
