# Generated by Django 5.2.5 on 2025-10-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db2_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchpatient',
            table='PATIENTS',
        ),
    ]
