# Generated by Django 5.2.5 on 2025-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db2_worker', '0002_history_researches_resultresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('KEY', models.TextField()),
                ('NM_SEX', models.TextField()),
                ('KEY_SEX', models.TextField(primary_key=True, serialize=False)),
                ('SEX', models.TextField()),
            ],
            options={
                'db_table': 'SEX',
                'managed': False,
            },
        ),
    ]
