from django.db import models


class Sex(models.Model):
    KEY = models.CharField(max_length=32, primary_key=True)
    NM_SEX = models.CharField(max_length=10, null=True, blank=True)
    KEY_SEX = models.IntegerField(null=True, blank=True)
    SEX = models.CharField(max_length=1, null=True, blank=True)

    class Meta:
        db_table = 'SEX'
        managed = False


class SearchPatient(models.Model):
    PATIENTNUMBER = models.CharField(max_length=20, primary_key=True)
    BDAY = models.DateTimeField(null=True, blank=True)
    CONTRACT = models.CharField(max_length=24, null=True, blank=True)
    PHONE = models.CharField(max_length=2469, null=True, blank=True)
    MIDDLENAME = models.CharField(max_length=95, null=True, blank=True)
    ADDRESSTYPE = models.CharField(max_length=4, null=True, blank=True)
    JURISTICPERSON = models.CharField(max_length=124, null=True, blank=True)
    LASTNAME = models.CharField(max_length=67, null=True, blank=True)
    ADDRESSTOWN = models.CharField(max_length=1670, null=True, blank=True)
    WORK = models.CharField(max_length=873, null=True, blank=True)
    DOCUMENTNUMBER = models.CharField(max_length=97, null=True, blank=True)
    FIRSTNAME = models.CharField(max_length=161, null=True, blank=True)
    #FORMOPLATA = models.CharField(max_length=5, null=True, blank=True)
    ADDRESSST = models.CharField(max_length=7, null=True, blank=True)
    SC_K = models.CharField(max_length=33, null=True, blank=True)
    ADDRESSRAION = models.CharField(max_length=62, null=True, blank=True)
    ADDRESSSTR = models.CharField(max_length=2998, null=True, blank=True)
    SC_SP = models.CharField(max_length=92, null=True, blank=True)
    PARTNERKEYLPU = models.CharField(max_length=32, null=True, blank=True)
    ISFIZICPERSON = models.CharField(max_length=17, null=True, blank=True)
    DOCUMENTSERIA = models.CharField(max_length=73, null=True, blank=True)
    STREET = models.CharField(max_length=1336, null=True, blank=True)
    ACCOUNT = models.CharField(max_length=2, null=True, blank=True)
    TBK = models.CharField(max_length=48, null=True, blank=True)
    ADDRESSFULL = models.CharField(max_length=3036, null=True, blank=True)
    RAION_GORODA = models.CharField(max_length=418, null=True, blank=True)
    SC_SP_KEY = models.CharField(max_length=92, null=True, blank=True)
    SEX = models.CharField(max_length=3, null=True, blank=True)
    YEARSOLD = models.IntegerField(null=True, blank=True)
    ADDRESSKEY = models.CharField(max_length=3, null=True, blank=True)
    KEY_ADDRESS_RAJON = models.IntegerField(null=True, blank=True)
    ADDRESSCLSKEY = models.CharField(max_length=23, null=True, blank=True)
    DATE_LPU = models.DateTimeField(null=True, blank=True)
    SNILSNUMBER = models.CharField(max_length=990, null=True, blank=True)
    AUTHOR = models.CharField(max_length=76, null=True, blank=True)
    MODIFIER = models.CharField(max_length=76, null=True, blank=True)
    MODIFIED = models.DateTimeField(null=True, blank=True)
    LASTAPPEAL = models.DateTimeField(null=True, blank=True)
    RESIDENTID = models.CharField(max_length=14, null=True, blank=True)
    RESIDENTDATE = models.DateTimeField(null=True, blank=True)
    RESIDENT = models.CharField(max_length=3, null=True, blank=True)
    KEY_LPU = models.CharField(max_length=51, null=True, blank=True)
    KEY_LPUATTACH = models.CharField(max_length=22, null=True, blank=True)
    EMAIL = models.CharField(max_length=38, null=True, blank=True)
    STARTNOEMAILDATE = models.DateTimeField(null=True, blank=True)
    NOEMAIL = models.IntegerField(null=True, blank=True)
    DOCTYPE = models.CharField(max_length=68, null=True, blank=True)
    DOCSERIA = models.CharField(max_length=324, null=True, blank=True)
    DOCNUMBER = models.CharField(max_length=84, null=True, blank=True)
    ADDRESSFULLR = models.CharField(max_length=176, null=True, blank=True)
    R1ID = models.CharField(max_length=18, null=True, blank=True)
    DOG_D = models.DateField(null=True, blank=True)
    DISC_CARD = models.SmallIntegerField(null=True, blank=True)
    DISCOUNTDATE = models.DateTimeField(null=True, blank=True)
    TOFIO = models.CharField(max_length=97, null=True, blank=True)
    TOPHONE = models.CharField(max_length=418, null=True, blank=True)
    TOKIND = models.CharField(max_length=74, null=True, blank=True)
    WORK_POSITION = models.CharField(max_length=259, null=True, blank=True)
    CONSENTMAILING = models.IntegerField(null=True, blank=True)
    DOCNAME = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        db_table = 'PATIENTS'
        managed = False


class History(models.Model):
    KEY = models.CharField(max_length=32, primary_key=True)
    FIRSTNAME = models.CharField(max_length=61, null=True, blank=True)
    MIDDLENAME = models.CharField(max_length=75, null=True, blank=True)
    LASTNAME = models.CharField(max_length=67, null=True, blank=True)
    HISTORYNUMBER = models.CharField(max_length=29, null=True, blank=True)
    ADDRESSST = models.CharField(max_length=20, null=True, blank=True)
    LPU = models.CharField(max_length=191, null=True, blank=True)
    SEX = models.CharField(max_length=9, null=True, blank=True)
    PATIENTNUMBER = models.CharField(max_length=30, null=True, blank=True)
    VRPO = models.CharField(max_length=32, null=True, blank=True)
    SC_IG = models.CharField(max_length=64, null=True, blank=True)
    VIZOV_SKOROI = models.CharField(max_length=5, null=True, blank=True)
    BIRTHDATE = models.DateTimeField(null=True, blank=True)
    ADDRESSTYPE = models.CharField(max_length=4, null=True, blank=True)
    VIZOV_SKOROI_ID = models.IntegerField(null=True, blank=True)
    KEY_LPU = models.CharField(max_length=32, null=True, blank=True)
    KEYADDRESSST = models.CharField(max_length=3, null=True, blank=True)
    KEY_PATIENTTYPE = models.CharField(max_length=14, null=True, blank=True)
    SEX_ID = models.IntegerField(null=True, blank=True)
    YEARSOLD = models.IntegerField(null=True, blank=True)
    CLOSED = models.IntegerField(null=True, blank=True)
    DCA_MKB = models.CharField(max_length=263, null=True, blank=True)
    KEY_ADDRESS_REGION = models.CharField(max_length=3, null=True, blank=True)
    KEY_IG = models.CharField(max_length=3, null=True, blank=True)
    STATUS = models.IntegerField(null=True, blank=True)
    D_INCOMING_MKB = models.CharField(max_length=250, null=True, blank=True)
    DC_MKB = models.CharField(max_length=69, null=True, blank=True)
    BOL_COUNT_DAYS = models.IntegerField(null=True, blank=True)
    CLOSEDDATE_LAST = models.DateTimeField(null=True, blank=True)
    HOSPATDATE_FIRST = models.DateTimeField(null=True, blank=True)
    PAUSE2DATE = models.DateTimeField(null=True, blank=True)
    ISMOVED = models.IntegerField(null=True, blank=True)
    REJECTNUMBER = models.CharField(max_length=7, null=True, blank=True)
    KEY_REJECTDEPARTMENT = models.CharField(max_length=78, null=True, blank=True)
    REJECTDOCTOR = models.CharField(max_length=197, null=True, blank=True)
    REJECTDATE = models.DateTimeField(null=True, blank=True)
    REJECTTYPE = models.CharField(max_length=451, null=True, blank=True)
    VIEWDATA = models.CharField(max_length=261, null=True, blank=True)
    D_LPU = models.CharField(max_length=3588, null=True, blank=True)
    SERVICES = models.CharField(max_length=4654, null=True, blank=True)
    JURISTICPERSON = models.CharField(max_length=123, null=True, blank=True)
    ISFIZICPERSON = models.CharField(max_length=43, null=True, blank=True)
    LDOCTOR = models.CharField(max_length=71, null=True, blank=True)
    HELPTYPE = models.CharField(max_length=55, null=True, blank=True)
    SC_K = models.CharField(max_length=47, null=True, blank=True)
    MODIFYDATE = models.DateTimeField(null=True, blank=True)
    DCA_SROK = models.IntegerField(null=True, blank=True)
    WHENOTDATE = models.DateTimeField(null=True, blank=True)
    WEB = models.IntegerField(null=True, blank=True)
    DCB_MKB = models.CharField(max_length=10, null=True, blank=True)
    DCC1_MKB = models.CharField(max_length=738, null=True, blank=True)
    DCC2_MKB = models.CharField(max_length=266, null=True, blank=True)
    SC_SP_KEY = models.CharField(max_length=20, null=True, blank=True)
    PATIENTTYPEDET = models.CharField(max_length=86, null=True, blank=True)
    DCAD = models.CharField(max_length=983, null=True, blank=True)
    DCAD_1 = models.CharField(max_length=1644, null=True, blank=True)
    DCAD_2_MKB = models.CharField(max_length=10, null=True, blank=True)
    DCAD_1_MKB = models.CharField(max_length=10, null=True, blank=True)
    DCAD_MKB = models.CharField(max_length=10, null=True, blank=True)
    DCAD_2 = models.CharField(max_length=624, null=True, blank=True)
    AUTOPSYREASON = models.CharField(max_length=2, null=True, blank=True)
    AUTOPSYREASONDOP = models.CharField(max_length=2, null=True, blank=True)
    MISMATCHKO_PAO = models.IntegerField(null=True, blank=True)
    AUTOPSYCATEGORY = models.CharField(max_length=2, null=True, blank=True)
    DIFCLINANDPAO = models.IntegerField(null=True, blank=True)
    DCC2_MES = models.CharField(max_length=39, null=True, blank=True)
    DC_MES = models.CharField(max_length=190, null=True, blank=True)
    DCC1_MES = models.CharField(max_length=88, null=True, blank=True)
    DCB_MES = models.CharField(max_length=19, null=True, blank=True)
    DATE_LPU = models.DateTimeField(null=True, blank=True)
    D_INCOMING_MES = models.CharField(max_length=88, null=True, blank=True)
    DCA_MES = models.CharField(max_length=24, null=True, blank=True)
    DC_SROK = models.IntegerField(null=True, blank=True)
    D_INCOMING_SROK = models.IntegerField(null=True, blank=True)
    SAMOOBRNUMBER = models.CharField(max_length=7, null=True, blank=True)
    KEY_HOSPDIRTYPE = models.CharField(max_length=20, null=True, blank=True)
    PATIENTSTATUS = models.CharField(max_length=56, null=True, blank=True)
    PATIENTSTATUSOTHER = models.CharField(max_length=42, null=True, blank=True)
    WORK = models.CharField(max_length=873, null=True, blank=True)
    SC_REZMP = models.CharField(max_length=15, null=True, blank=True)
    DD_IZ = models.CharField(max_length=26, null=True, blank=True)
    F1 = models.IntegerField(null=True, blank=True)
    DELAYSTANDARTKEY = models.CharField(max_length=38, null=True, blank=True)
    DELAYOPERKEY = models.CharField(max_length=26, null=True, blank=True)
    COMPETEDEASEAS = models.CharField(max_length=3, null=True, blank=True)
    PATIENTMOOVED = models.CharField(max_length=3, null=True, blank=True)
    DCP = models.CharField(max_length=2712, null=True, blank=True)
    KEY_DELIVERYTIME = models.CharField(max_length=19, null=True, blank=True)
    INCOMINGTYPE = models.CharField(max_length=10, null=True, blank=True)
    SERIOUSCASES = models.CharField(max_length=3, null=True, blank=True)
    D_INCOMING_KSG = models.CharField(max_length=21, null=True, blank=True)
    DCA_KSG = models.CharField(max_length=21, null=True, blank=True)
    DCB_KSG = models.CharField(max_length=21, null=True, blank=True)
    DCC2_KSG = models.CharField(max_length=21, null=True, blank=True)
    DCC1_KSG = models.CharField(max_length=73, null=True, blank=True)
    DC_KSG = models.CharField(max_length=32, null=True, blank=True)
    PAUSE2TIME = models.DateTimeField(null=True, blank=True)
    KILLIP = models.IntegerField(null=True, blank=True)
    SICKTYPE = models.CharField(max_length=9, null=True, blank=True)
    SICKTIME = models.CharField(max_length=26, null=True, blank=True)
    HOSPATDATE_FIRST_D = models.DateField(null=True, blank=True)
    CLOSEDDATE_LAST_D = models.DateField(null=True, blank=True)
    ISTRANSFERLPU = models.CharField(max_length=3, null=True, blank=True)

    class Meta:
        db_table = 'HISTORY'
        managed = False


class Researches(models.Model):
    KEY = models.CharField(max_length=50, primary_key=True)
    ID = models.IntegerField()
    KEY_PATIENTTYPE = models.CharField(max_length=13, null=True, blank=True)
    KIS_KEY = models.CharField(max_length=64)
    EXECUTOR_EMPLOYEE_KIS_KEY = models.CharField(max_length=64)
    DEPARTMENTKEY = models.CharField(max_length=58, null=True, blank=True)
    DEPARTMENTL = models.CharField(max_length=1, null=True, blank=True)
    EXECUTOR_EMPLOYEE_NAME = models.CharField(max_length=256)
    RESEARCHDATETIME = models.DateTimeField(null=True, blank=True)
    CLOSED = models.IntegerField(null=True, blank=True)
    STATUS = models.IntegerField(null=True, blank=True)
    PARENTSTATUS = models.IntegerField(null=True, blank=True)
    KEY_RESEARCHTYPE = models.CharField(max_length=50, null=True, blank=True)
    KEY_HISTORY = models.CharField(max_length=64, null=True, blank=True)
    YEARSOLD = models.IntegerField(null=True, blank=True)
    QUOTE = models.CharField(max_length=261, null=True, blank=True)
    REQUESTDOCTOR = models.CharField(max_length=208, null=True, blank=True)
    RESEARCHDEPARTMENTKEY = models.CharField(max_length=100, null=True, blank=True)
    PATIENTNUMBER = models.CharField(max_length=28, null=True, blank=True)
    TOOLCODE = models.CharField(max_length=50, null=True, blank=True)
    CODE = models.CharField(max_length=12, null=True, blank=True)
    PAYMENTFORM = models.CharField(max_length=44, null=True, blank=True)
    COST = models.IntegerField(null=True, blank=True)
    JURISTICPERSON = models.CharField(max_length=121, null=True, blank=True)
    PATIENTTYPEDET = models.CharField(max_length=72, null=True, blank=True)
    PAYSTATUS = models.CharField(max_length=2, null=True, blank=True)
    AUTHOR = models.CharField(max_length=33, null=True, blank=True)
    PKO = models.CharField(max_length=11, null=True, blank=True)
    COSTCASS = models.CharField(max_length=20, null=True, blank=True)
    ML = models.CharField(max_length=22, null=True, blank=True)
    NOTEID = models.CharField(max_length=10, null=True, blank=True)
    CREATED = models.DateTimeField(null=True, blank=True)
    ISACT = models.CharField(max_length=1, null=True, blank=True)
    PARENTKEY = models.CharField(max_length=1, null=True, blank=True)
    SERVICETYPE = models.CharField(max_length=20, null=True, blank=True)
    COSTWITHDISCOUNT = models.IntegerField(null=True, blank=True)
    COM = models.IntegerField(null=True, blank=True)
    CITO = models.CharField(max_length=10, null=True, blank=True)
    RSERVICESUBTYPEKEY = models.CharField(max_length=50, null=True, blank=True)
    RSERVICETYPEKEY = models.CharField(max_length=50, null=True, blank=True)
    STANDARTKEY = models.CharField(max_length=50, null=True, blank=True)
    ASSIGNFROM = models.CharField(max_length=50, null=True, blank=True)
    OPERCODE = models.CharField(max_length=17, null=True, blank=True)
    COMPLITEDPT = models.CharField(max_length=8, null=True, blank=True)
    VMP = models.IntegerField(null=True, blank=True)
    SERVICEID = models.CharField(max_length=50, null=True, blank=True)
    COMPLITEDAT = models.DateTimeField(null=True, blank=True)
    SERVICECOUNT = models.IntegerField(null=True, blank=True)
    MAINPROFILEKEY = models.CharField(max_length=48, null=True, blank=True)
    STANDARTYEAR = models.IntegerField(null=True, blank=True)
    PACKKEY = models.CharField(max_length=32, null=True, blank=True)
    ACTUALDATETIME = models.DateTimeField(null=True, blank=True)
    DOCMODIFIED = models.DateTimeField(null=True, blank=True)
    SERVICEPACKPLANID = models.CharField(max_length=32, null=True, blank=True)
    F1 = models.IntegerField(null=True, blank=True)
    ASSIGNRESULTKEY = models.CharField(max_length=27, null=True, blank=True)
    DICOMACCESSIONNUMBER = models.CharField(max_length=13, null=True, blank=True)
    UNSIGNEDPROTOCOL = models.IntegerField(null=True, blank=True)
    REJECTDATE = models.DateTimeField(null=True, blank=True)
    REJECTNAME = models.CharField(max_length=886, null=True, blank=True)
    DINCONSNUM = models.CharField(max_length=7, null=True, blank=True)
    COMMENT_MEDREG = models.CharField(max_length=1689, null=True, blank=True)
    REJECTKEY = models.CharField(max_length=10, null=True, blank=True)
    MAINPACKSERVICE = models.IntegerField(null=True, blank=True)
    ASSIGNCLOSEDKEY = models.CharField(max_length=32, null=True, blank=True)
    DIRECTIONLPU = models.CharField(max_length=20, null=True, blank=True)
    ISMKBDISC = models.CharField(max_length=1, null=True, blank=True)
    LAB_REQUEST_CODE = models.CharField(max_length=50, null=True, blank=True)
    COMEINAT = models.DateTimeField(null=True, blank=True)
    RESEARCHTARGET = models.CharField(max_length=1909, null=True, blank=True)
    RESEARCH_CATEGORY = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        db_table = 'RESEARCHES'
        managed = False


class ResultResearch(models.Model):
    KEY = models.CharField(max_length=32, primary_key=True)
    RESULTDOCTOR = models.CharField(max_length=1193, null=True, blank=True)
    KEY_RESEARCH_TYPE = models.CharField(max_length=32, null=True, blank=True)
    KEY_RESEARCH = models.CharField(max_length=164, null=True, blank=True)
    RESULTNURSE = models.CharField(max_length=1962, null=True, blank=True)
    KEY_DINTEMPLATEVER = models.CharField(max_length=32, null=True, blank=True)
    OPERTYPEKEY = models.CharField(max_length=24, null=True, blank=True)
    F1 = models.IntegerField(null=True, blank=True)
    SIGNED = models.IntegerField(null=True, blank=True)
    STARTDININSPDATE = models.DateTimeField(null=True, blank=True)
    CONSULTATIONNUMBER = models.CharField(max_length=10, null=True, blank=True)
    MKB = models.CharField(max_length=26, null=True, blank=True)
    OPERSTARTDT = models.DateTimeField(null=True, blank=True)
    OPERENDDT = models.DateTimeField(null=True, blank=True)
    EYES_COLOR = models.CharField(max_length=35, null=True, blank=True)
    FIRST_SIGNER = models.CharField(max_length=74, null=True, blank=True)
    DRUG_THERAPY_DOP = models.CharField(max_length=2827, null=True, blank=True)
    OPERNARCOSIS = models.CharField(max_length=1, null=True, blank=True)
    ANASTTYPE = models.CharField(max_length=2, null=True, blank=True)
    RESULTFORMZAKL = models.CharField(max_length=21056, null=True, blank=True)
    CLINIC_CARD_NUMBER = models.CharField(max_length=31, null=True, blank=True)

    class Meta:
        db_table = 'RESEARCH_RESULTSR2'
        managed = False