from django.db import models

class SearchPatient(models.Model):
    # Описать таблицу как она лежит в медстате
    '''
    s_name = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=50, null=True)
    surname = models.CharField(max_length=50, null=True)
    gender = models.CharField(max_length=20, null=True)
    date_birth = models.DateField(null=True)
    p_series = models.CharField(max_length=50, null=True)
    p_number = models.CharField(max_length=50, null=True)
    snils = models.CharField(max_length=50, null=True)
    med_polis = models.CharField(max_length=50, null=True)
    medstat_id = models.CharField(max_length=50, null=True)
    '''
    PATIENTNUMBER = models.TextField()
    BDAY = models.TextField()
    CONTRACT = models.TextField()
    PHONE = models.TextField()
    MIDDLENAME = models.TextField()
    ADDRESSTYPE = models.TextField()
    JURISTICPERSON = models.TextField()
    LASTNAME = models.TextField()
    ADDRESSTOWN = models.TextField()
    WORK = models.TextField()
    DOCUMENTNUMBER = models.TextField()
    FIRSTNAME = models.TextField()
    FORMAOPLATA = models.TextField()
    ADDRESSST = models.TextField()
    SC_K = models.TextField()
    ADDRESSRAION = models.TextField()
    ADDRESSSTR = models.TextField()
    SC_SP = models.TextField()
    PARTNERKEYLPU = models.TextField()
    ISFIZICPERSON = models.TextField()
    DOCUMENTSERIA = models.TextField()
    STREET = models.TextField()
    ACCOUNT = models.TextField()
    TBK = models.TextField()
    ADDRESSFULL = models.TextField()
    RAION_GORODA = models.TextField()
    SC_SP_KEY = models.TextField()
    SEX = models.TextField()
    YEARSOLD = models.TextField()
    ADDRESSKEY = models.TextField()
    KEY_ADDRESS_RAJON = models.TextField()
    ADDRESSCLSKEY = models.TextField()
    DATE_LPU = models.TextField()
    SNILSNUMBER = models.TextField()
    AUTHOR = models.TextField()
    MODIFIER = models.TextField()
    MODIFIED = models.TextField()
    LASTAPPEAL = models.TextField()
    RESIDENTID = models.TextField()
    RESIDENTDATE = models.TextField()
    RESIDENT = models.TextField()
    KEY_LPU = models.TextField()
    KEY_LPUATTACH = models.TextField()
    EMAIL = models.TextField()
    STARTNOEMAILDATE = models.TextField()
    NOEMAIL = models.TextField()
    DOCTYPE = models.TextField()
    DOCSERIA = models.TextField()
    DOCNUMBER = models.TextField()
    ADDRESSFULLR = models.TextField()
    R1ID = models.TextField()
    DOG_D = models.TextField()
    DISC_CARD = models.TextField()
    DISCOUNTDATE = models.TextField()
    TOFIO = models.TextField()
    TOPHONE = models.TextField()
    TOKIND = models.TextField()
    WORK_POSITION = models.TextField()
    CONSENTMAILING = models.TextField()
    DOCNAME = models.TextField()

    class Meta:
        db_table = 'PATIENTS' # название таблицы как в медстате
        managed = False # данный метод не создаёт таблицу в медстате