from django.db import models

class Sex(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    nm_sex = models.CharField(max_length=10, null=True, blank=True)
    key_sex = models.IntegerField(null=True, blank=True)
    sex = models.CharField(max_length=1, null=True, blank=True)

    class Meta:
        db_table = 'SEX' # название таблицы как в базе даныых "медстате"
        managed = False # данный метод не создаёт таблицу в базе данных "медстат"


class SearchPatient(models.Model):
    patientnumber = models.CharField(max_length=20, primary_key=True)
    bday = models.DateTimeField(null=True, blank=True)
    contract = models.CharField(max_length=24, null=True, blank=True)
    phone = models.CharField(max_length=2469, null=True, blank=True)
    middlename = models.CharField(max_length=95, null=True, blank=True)
    addresstype = models.CharField(max_length=4, null=True, blank=True)
    juristicperson = models.CharField(max_length=124, null=True, blank=True)
    lastname = models.CharField(max_length=67, null=True, blank=True)
    addresstown = models.CharField(max_length=1670, null=True, blank=True)
    work = models.CharField(max_length=873, null=True, blank=True)
    documentnumber = models.CharField(max_length=97, null=True, blank=True)
    firstname = models.CharField(max_length=161, null=True, blank=True)
    formaoplata = models.CharField(max_length=5, null=True, blank=True)
    addressst = models.CharField(max_length=7, null=True, blank=True)
    sc_k = models.CharField(max_length=33, null=True, blank=True)
    addressraion = models.CharField(max_length=62, null=True, blank=True)
    addressstr = models.CharField(max_length=2998, null=True, blank=True)
    sc_sp = models.CharField(max_length=92, null=True, blank=True)
    partnerkeylpu = models.CharField(max_length=32, null=True, blank=True)
    isfizicperson = models.CharField(max_length=17, null=True, blank=True)
    documentseria = models.CharField(max_length=73, null=True, blank=True)
    street = models.CharField(max_length=1336, null=True, blank=True)
    account = models.CharField(max_length=2, null=True, blank=True)
    tbk = models.CharField(max_length=48, null=True, blank=True)
    addressfull = models.CharField(max_length=3036, null=True, blank=True)
    raion_goroda = models.CharField(max_length=418, null=True, blank=True)
    sc_sp_key = models.CharField(max_length=92, null=True, blank=True)
    sex = models.CharField(max_length=3, null=True, blank=True)
    yearsold = models.IntegerField(null=True, blank=True)
    addresskey = models.CharField(max_length=3, null=True, blank=True)
    key_address_rajon = models.IntegerField(null=True, blank=True)
    addressclskey = models.CharField(max_length=23, null=True, blank=True)
    date_lpu = models.DateTimeField(null=True, blank=True)
    snilsnumber = models.CharField(max_length=990, null=True, blank=True)
    author = models.CharField(max_length=76, null=True, blank=True)
    modifier = models.CharField(max_length=76, null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    lastappeal = models.DateTimeField(null=True, blank=True)
    residentid = models.CharField(max_length=14, null=True, blank=True)
    residentdate = models.DateTimeField(null=True, blank=True)
    resident = models.CharField(max_length=3, null=True, blank=True)
    key_lpu = models.CharField(max_length=51, null=True, blank=True)
    key_lpuattach = models.CharField(max_length=22, null=True, blank=True)
    email = models.CharField(max_length=38, null=True, blank=True)
    startnoemaildate = models.DateTimeField(null=True, blank=True)
    noemail = models.IntegerField(null=True, blank=True)
    doctype = models.CharField(max_length=68, null=True, blank=True)
    docseria = models.CharField(max_length=324, null=True, blank=True)
    docnumber = models.CharField(max_length=84, null=True, blank=True)
    addressfullr = models.CharField(max_length=176, null=True, blank=True)
    r1id = models.CharField(max_length=18, null=True, blank=True)
    dog_d = models.DateField(null=True, blank=True)
    disc_card = models.SmallIntegerField(null=True, blank=True)
    discountdate = models.DateTimeField(null=True, blank=True)
    tofio = models.CharField(max_length=97, null=True, blank=True)
    tophone = models.CharField(max_length=418, null=True, blank=True)
    tokind = models.CharField(max_length=74, null=True, blank=True)
    work_position = models.CharField(max_length=259, null=True, blank=True)
    consentmailing = models.IntegerField(null=True, blank=True)
    docname = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        db_table = 'PATIENTS'
        managed = False


class History(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    firstname = models.CharField(max_length=61, null=True, blank=True)
    middlename = models.CharField(max_length=75, null=True, blank=True)
    lastname = models.CharField(max_length=67, null=True, blank=True)
    historynumber = models.CharField(max_length=29, null=True, blank=True)
    addressst = models.CharField(max_length=20, null=True, blank=True)
    lpu = models.CharField(max_length=191, null=True, blank=True)
    sex = models.CharField(max_length=9, null=True, blank=True)
    patientnumber = models.CharField(max_length=30, null=True, blank=True)
    vrpo = models.CharField(max_length=32, null=True, blank=True)
    sc_ig = models.CharField(max_length=64, null=True, blank=True)
    vizov_skoroi = models.CharField(max_length=5, null=True, blank=True)
    birthdate = models.DateTimeField(null=True, blank=True)
    addresstype = models.CharField(max_length=4, null=True, blank=True)
    vizov_skoroi_id = models.IntegerField(null=True, blank=True)
    key_lpu = models.CharField(max_length=32, null=True, blank=True)
    keyaddressst = models.CharField(max_length=3, null=True, blank=True)
    key_patienttype = models.CharField(max_length=14, null=True, blank=True)
    sex_id = models.IntegerField(null=True, blank=True)
    yearsold = models.IntegerField(null=True, blank=True)
    closed = models.IntegerField(null=True, blank=True)
    dca_mkb = models.CharField(max_length=263, null=True, blank=True)
    key_address_region = models.CharField(max_length=3, null=True, blank=True)
    key_ig = models.CharField(max_length=3, null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    d_incoming_mkb = models.CharField(max_length=250, null=True, blank=True)
    dc_mkb = models.CharField(max_length=69, null=True, blank=True)
    bol_count_days = models.IntegerField(null=True, blank=True)
    closeddate_last = models.DateTimeField(null=True, blank=True)
    hospatdate_first = models.DateTimeField(null=True, blank=True)
    pause2date = models.DateTimeField(null=True, blank=True)
    ismoved = models.IntegerField(null=True, blank=True)
    rejectnumber = models.CharField(max_length=7, null=True, blank=True)
    key_rejectdepartment = models.CharField(max_length=78, null=True, blank=True)
    rejectdoctor = models.CharField(max_length=197, null=True, blank=True)
    rejectdate = models.DateTimeField(null=True, blank=True)
    rejecttype = models.CharField(max_length=451, null=True, blank=True)
    viewdata = models.CharField(max_length=261, null=True, blank=True)
    d_lpu = models.CharField(max_length=3588, null=True, blank=True)
    services = models.CharField(max_length=4654, null=True, blank=True)
    juristicperson = models.CharField(max_length=123, null=True, blank=True)
    isfizicperson = models.CharField(max_length=43, null=True, blank=True)
    ldoctor = models.CharField(max_length=71, null=True, blank=True)
    helptype = models.CharField(max_length=55, null=True, blank=True)
    sc_k = models.CharField(max_length=47, null=True, blank=True)
    modifydate = models.DateTimeField(null=True, blank=True)
    dca_srok = models.IntegerField(null=True, blank=True)
    whenotdate = models.DateTimeField(null=True, blank=True)
    web = models.IntegerField(null=True, blank=True)
    dcb_mkb = models.CharField(max_length=10, null=True, blank=True)
    dcc1_mkb = models.CharField(max_length=738, null=True, blank=True)
    dcc2_mkb = models.CharField(max_length=266, null=True, blank=True)
    sc_sp_key = models.CharField(max_length=20, null=True, blank=True)
    patienttypedet = models.CharField(max_length=86, null=True, blank=True)
    dcad = models.CharField(max_length=983, null=True, blank=True)
    dcad_1 = models.CharField(max_length=1644, null=True, blank=True)
    dcad_2_mkb = models.CharField(max_length=10, null=True, blank=True)
    dcad_1_mkb = models.CharField(max_length=10, null=True, blank=True)
    dcad_mkb = models.CharField(max_length=10, null=True, blank=True)
    dcad_2 = models.CharField(max_length=624, null=True, blank=True)
    autopsyreason = models.CharField(max_length=2, null=True, blank=True)
    autopsyreasondop = models.CharField(max_length=2, null=True, blank=True)
    mismatchko_pao = models.IntegerField(null=True, blank=True)
    autopsycategory = models.CharField(max_length=2, null=True, blank=True)
    difclinandpao = models.IntegerField(null=True, blank=True)
    dcc2_mes = models.CharField(max_length=39, null=True, blank=True)
    dc_mes = models.CharField(max_length=190, null=True, blank=True)
    dcc1_mes = models.CharField(max_length=88, null=True, blank=True)
    dcb_mes = models.CharField(max_length=19, null=True, blank=True)
    date_lpu = models.DateTimeField(null=True, blank=True)
    d_incoming_mes = models.CharField(max_length=88, null=True, blank=True)
    dca_mes = models.CharField(max_length=24, null=True, blank=True)
    dc_srok = models.IntegerField(null=True, blank=True)
    d_incoming_srok = models.IntegerField(null=True, blank=True)
    samoobrnumber = models.CharField(max_length=7, null=True, blank=True)
    key_hospdirtype = models.CharField(max_length=20, null=True, blank=True)
    patientstatus = models.CharField(max_length=56, null=True, blank=True)
    patientstatusother = models.CharField(max_length=42, null=True, blank=True)
    work = models.CharField(max_length=873, null=True, blank=True)
    sc_rezmp = models.CharField(max_length=15, null=True, blank=True)
    dd_iz = models.CharField(max_length=26, null=True, blank=True)
    f1 = models.IntegerField(null=True, blank=True)
    delaystandartkey = models.CharField(max_length=38, null=True, blank=True)
    delayoperkey = models.CharField(max_length=26, null=True, blank=True)
    competedeaseas = models.CharField(max_length=3, null=True, blank=True)
    patientmooved = models.CharField(max_length=3, null=True, blank=True)
    dcp = models.CharField(max_length=2712, null=True, blank=True)
    key_deliverytime = models.CharField(max_length=19, null=True, blank=True)
    incomingtype = models.CharField(max_length=10, null=True, blank=True)
    seriouscases = models.CharField(max_length=3, null=True, blank=True)
    d_incoming_ksg = models.CharField(max_length=21, null=True, blank=True)
    dca_ksg = models.CharField(max_length=21, null=True, blank=True)
    dcb_ksg = models.CharField(max_length=21, null=True, blank=True)
    dcc2_ksg = models.CharField(max_length=21, null=True, blank=True)
    dcc1_ksg = models.CharField(max_length=73, null=True, blank=True)
    dc_ksg = models.CharField(max_length=32, null=True, blank=True)
    pause2time = models.DateTimeField(null=True, blank=True)
    killip = models.IntegerField(null=True, blank=True)
    sicktype = models.CharField(max_length=9, null=True, blank=True)
    sicktime = models.CharField(max_length=26, null=True, blank=True)
    hospatdate_first_d = models.DateField(null=True, blank=True)
    closeddate_last_d = models.DateField(null=True, blank=True)
    istransferlpu = models.CharField(max_length=3, null=True, blank=True)

    class Meta:
        db_table = 'HISTORY'
        managed = False


class Researches(models.Model):
    key = models.CharField(max_length=50, primary_key=True)
    id = models.IntegerField()
    key_patienttype = models.CharField(max_length=13, null=True, blank=True)
    kis_key = models.CharField(max_length=64)
    executor_employee_kis_key = models.CharField(max_length=64)
    departmentkey = models.CharField(max_length=58, null=True, blank=True)
    departmentl = models.CharField(max_length=1, null=True, blank=True)
    executor_employee_name = models.CharField(max_length=256)
    researchdatetime = models.DateTimeField(null=True, blank=True)
    closed = models.IntegerField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    parentstatus = models.IntegerField(null=True, blank=True)
    key_researchtype = models.CharField(max_length=50, null=True, blank=True)
    key_history = models.CharField(max_length=64, null=True, blank=True)
    yearsold = models.IntegerField(null=True, blank=True)
    quote = models.CharField(max_length=261, null=True, blank=True)
    requestdoctor = models.CharField(max_length=208, null=True, blank=True)
    researchdepartmentkey = models.CharField(max_length=100, null=True, blank=True)
    patientnumber = models.CharField(max_length=28, null=True, blank=True)
    toolcode = models.CharField(max_length=50, null=True, blank=True)
    code = models.CharField(max_length=12, null=True, blank=True)
    paymentform = models.CharField(max_length=44, null=True, blank=True)
    cost = models.IntegerField(null=True, blank=True)
    juristicperson = models.CharField(max_length=121, null=True, blank=True)
    patienttypedet = models.CharField(max_length=72, null=True, blank=True)
    paystatus = models.CharField(max_length=2, null=True, blank=True)
    author = models.CharField(max_length=33, null=True, blank=True)
    pko = models.CharField(max_length=11, null=True, blank=True)
    costcass = models.CharField(max_length=20, null=True, blank=True)
    ml = models.CharField(max_length=22, null=True, blank=True)
    noteid = models.CharField(max_length=10, null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    isact = models.CharField(max_length=1, null=True, blank=True)
    parentkey = models.CharField(max_length=1, null=True, blank=True)
    servicetype = models.CharField(max_length=20, null=True, blank=True)
    costwithdiscount = models.IntegerField(null=True, blank=True)
    com = models.IntegerField(null=True, blank=True)
    cito = models.CharField(max_length=10, null=True, blank=True)
    rservicesubtypekey = models.CharField(max_length=50, null=True, blank=True)
    rservicetypekey = models.CharField(max_length=50, null=True, blank=True)
    standartkey = models.CharField(max_length=50, null=True, blank=True)
    assignfrom = models.CharField(max_length=50, null=True, blank=True)
    opercode = models.CharField(max_length=17, null=True, blank=True)
    complitedpt = models.CharField(max_length=8, null=True, blank=True)
    vmp = models.IntegerField(null=True, blank=True)
    serviceid = models.CharField(max_length=50, null=True, blank=True)
    complitedat = models.DateTimeField(null=True, blank=True)
    servicecount = models.IntegerField(null=True, blank=True)
    mainprofilekey = models.CharField(max_length=48, null=True, blank=True)
    standartyear = models.IntegerField(null=True, blank=True)
    packkey = models.CharField(max_length=32, null=True, blank=True)
    actualdatetime = models.DateTimeField(null=True, blank=True)
    docmodified = models.DateTimeField(null=True, blank=True)
    servicepackplanid = models.CharField(max_length=32, null=True, blank=True)
    f1 = models.IntegerField(null=True, blank=True)
    assignresultkey = models.CharField(max_length=27, null=True, blank=True)
    dicomaccessionnumber = models.CharField(max_length=13, null=True, blank=True)
    unsignedprotocol = models.IntegerField(null=True, blank=True)
    rejectdate = models.DateTimeField(null=True, blank=True)
    rejectname = models.CharField(max_length=886, null=True, blank=True)
    dinconsnum = models.CharField(max_length=7, null=True, blank=True)
    comment_medreg = models.CharField(max_length=1689, null=True, blank=True)
    rejectkey = models.CharField(max_length=10, null=True, blank=True)
    mainpackservice = models.IntegerField(null=True, blank=True)
    assignclosedkey = models.CharField(max_length=32, null=True, blank=True)
    directionlpu = models.CharField(max_length=20, null=True, blank=True)
    ismkbdisc = models.CharField(max_length=1, null=True, blank=True)
    lab_request_code = models.CharField(max_length=50, null=True, blank=True)
    comeinat = models.DateTimeField(null=True, blank=True)
    researchtarget = models.CharField(max_length=1909, null=True, blank=True)
    research_category = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        db_table = 'RESEARCHES'
        managed = False


class ResultResearch(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    resultdoctor = models.CharField(max_length=1193, null=True, blank=True)
    key_research_type = models.CharField(max_length=32, null=True, blank=True)
    key_research = models.CharField(max_length=164, null=True, blank=True)
    resultnurse = models.CharField(max_length=1962, null=True, blank=True)
    key_dintemplatever = models.CharField(max_length=32, null=True, blank=True)
    opertypekey = models.CharField(max_length=24, null=True, blank=True)
    f1 = models.IntegerField(null=True, blank=True)
    signed = models.IntegerField(null=True, blank=True)
    startdininspdate = models.DateTimeField(null=True, blank=True)
    consultationnumber = models.CharField(max_length=10, null=True, blank=True)
    mkb = models.CharField(max_length=26, null=True, blank=True)
    operstartdt = models.DateTimeField(null=True, blank=True)
    operenddt = models.DateTimeField(null=True, blank=True)
    eyes_color = models.CharField(max_length=35, null=True, blank=True)
    first_signer = models.CharField(max_length=74, null=True, blank=True)
    drug_therapy_dop = models.CharField(max_length=2827, null=True, blank=True)
    opernarcosis = models.CharField(max_length=1, null=True, blank=True)
    anasttype = models.CharField(max_length=2, null=True, blank=True)
    resultformzakl = models.CharField(max_length=21056, null=True, blank=True)
    clinic_card_number = models.CharField(max_length=31, null=True, blank=True)

    class Meta:
        db_table = 'RESEARCH_RESULTSR2'
        managed = False

