# Generated by Django 5.2.5 on 2025-09-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'deviation',
            },
        ),
        migrations.CreateModel(
            name='Dynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'dynamics',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'organ',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='POTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'potc',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'rec',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.CreateModel(
            name='TOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'tod',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'weight',
            },
        ),
        migrations.CreateModel(
            name='DOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(null=True)),
                ('age_max', models.IntegerField(null=True)),
                ('norm_min', models.CharField(max_length=50, null=True)),
                ('norm_max', models.CharField(max_length=50, null=True)),
                ('mod_dev_min', models.CharField(max_length=50, null=True)),
                ('mod_dev_max', models.CharField(max_length=50, null=True)),
                ('exp_dev_min', models.CharField(max_length=50, null=True)),
                ('exp_dev_max', models.CharField(max_length=50, null=True)),
                ('crit_dev_min', models.CharField(max_length=50, null=True)),
                ('crit_dev_max', models.CharField(max_length=50, null=True)),
                ('deviation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.deviation')),
                ('neg_dyn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negative_dyn', to='KDLApi.dynamics')),
                ('pos_dyn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positive_dyn', to='KDLApi.dynamics')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.gender')),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.organ')),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.parameter')),
                ('potc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.potc')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.priority')),
                ('rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.rec')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.state')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.system')),
                ('tod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.tod')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.weight')),
            ],
            options={
                'db_table': 'dos',
            },
        ),
    ]
