# Generated by Django 5.2.5 on 2025-08-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDLApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dos',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.priority'),
        ),
    ]
