# Generated by Django 5.2.5 on 2025-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDLApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dos',
            name='consectary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
