# Generated by Django 5.2.5 on 2025-11-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDLApi', '0002_dos_consectary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consectary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'consectary',
            },
        ),
        migrations.AlterField(
            model_name='dos',
            name='consectary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KDLApi.consectary'),
        ),
    ]
