# Generated by Django 5.2.5 on 2025-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDLApi', '0002_dos_priority'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviation',
            table='deviation',
        ),
        migrations.AlterModelTable(
            name='dos',
            table='dos',
        ),
        migrations.AlterModelTable(
            name='dynamics',
            table='dynamics',
        ),
        migrations.AlterModelTable(
            name='gender',
            table='gender',
        ),
        migrations.AlterModelTable(
            name='organ',
            table='organ',
        ),
        migrations.AlterModelTable(
            name='parameter',
            table='parameter',
        ),
        migrations.AlterModelTable(
            name='potc',
            table='potc',
        ),
        migrations.AlterModelTable(
            name='priority',
            table='priority',
        ),
        migrations.AlterModelTable(
            name='rec',
            table='rec',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
        migrations.AlterModelTable(
            name='system',
            table='system',
        ),
        migrations.AlterModelTable(
            name='tod',
            table='tod',
        ),
        migrations.AlterModelTable(
            name='weight',
            table='weight',
        ),
    ]
