# Generated by Django 5.2.5 on 2025-09-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_save', models.DateTimeField(auto_now=True)),
                ('inter_result', models.TextField(null=True)),
                ('conc_text', models.TextField(null=True)),
                ('conc_file', models.FilePathField(null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.research')),
            ],
            options={
                'db_table': 'conclusion',
            },
        ),
    ]
