# Generated by Django 5.2.5 on 2025-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conclusion',
            table='conclusion',
        ),
    ]
