# Generated by Django 5.2.5 on 2025-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ad',
            table='ad',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='employer',
            table='employer',
        ),
        migrations.AlterModelTable(
            name='jt',
            table='jt',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
