# Generated by Django 5.2.5 on 2025-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='login',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='pwd',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
