export const glossaries = [
    {id: 'system', title: 'Система'},
    {id: 'organ', title: 'Орган'},
    {id: 'state', title: 'Состояния'},
    {id: 'parameter', title: 'Параметры'},
    {id: 'priority', title: 'Приоритет параметра'},
    {id: 'weight', title: 'Значимость параметра'},
    {id: 'gender', title: 'Пол'},
    {id: 'potc', title: 'Фаза цикла'},
    {id: 'tod', title: 'Единицы измерения'},
    {id: 'deviation', title: 'Отклонение'},
    {id: 'dynamics', title: 'Динамика'},
    {id: 'rec', title: 'Рекомендации'},
];

export const glossaries_shared = [
    {id: 'system', title: 'Система'},
    {id: 'organ', title: 'Орган'},
    {id: 'state', title: 'Состояния'},
    {id: 'parameter', title: 'Параметры'},
    {id: 'priority', title: 'Приоритет параметра'},
    {id: 'weight', title: 'Значимость параметра'},
    {id: 'gender', title: 'Пол'},
    {id: 'age_min', title: 'Возраст минимум'},
    {id: 'age_max', title: 'Возраст максимум'},
    {id: 'potc', title: 'Фаза цикла'},
    {id: 'tod', title: 'Единицы измерения'},
    {id: 'norm_min', title: 'Норма минимум'},
    {id: 'norm_max', title: 'Норма максимум'},
    {id: 'mod_dev_min', title: 'Умеренные минимум'},
    {id: 'mod_dev_max', title: 'Умеренные максимум'},
    {id: 'exp_dev_min', title: 'Выраженные минимум'},
    {id: 'exp_dev_max', title: 'Выраженные максимум'},
    {id: 'crit_dev_min', title: 'Критические минимум'},
    {id: 'crit_dev_max', title: 'Критические максимум'},
    {id: 'deviation', title: 'Отклонение'},
    {id: "pos_dyn", title: "Положительная динамика" },
    {id: "neg_dyn", title: "Отрицательная динамика" },
    {id: 'rec', title: 'Рекомендации'},
];