# Generated by Django 5.2.5 on 2025-09-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('p_series', models.CharField(max_length=50, null=True)),
                ('p_number', models.CharField(max_length=50, null=True)),
                ('snils', models.CharField(max_length=50, null=True)),
                ('med_polis', models.CharField(max_length=50, null=True)),
                ('medstat_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('research_name', models.CharField(max_length=50, null=True)),
                ('data', models.TextField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'research',
            },
        ),
    ]
