# Generated by Django 5.2.5 on 2025-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='research',
            table='research',
        ),
    ]
